export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS";
export const ADD_ASSOCIATE = "ADD_ASSOCIATE";
export const GET_ASSOCIATE_ID = "GET_ASSOCIATE_ID";
export const ADD_ASSOCIATE_OBJECT = "ADD_ASSOCIATE_OBJECT"
export const LOGOUT_USER = "LOGOUT_USER";
export const GET_DESTINATION = "GET_DESTINATION";