-- MySQL Script generated by MySQL Workbench
-- Tue Jul 23 11:28:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AccountOwner
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AccountOwner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AccountOwner` DEFAULT CHARACTER SET utf8 ;
USE `AccountOwner` ;

-- -----------------------------------------------------
-- Table `AccountOwner`.`Owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccountOwner`.`Owner` ;

CREATE TABLE IF NOT EXISTS `AccountOwner`.`Owner` (
  `OwnerId` INT NOT NULL,
  `Name` NVARCHAR(60) NOT NULL,
  `DateofBirth` DATE NOT NULL,
  `Address` NVARCHAR(100) NOT NULL,
  PRIMARY KEY (`OwnerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AccountOwner`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AccountOwner`.`Account` ;

CREATE TABLE IF NOT EXISTS `AccountOwner`.`Account` (
  `AccountId` CHAR(36) NOT NULL,
  `DateCreated` DATE NOT NULL,
  `AccountType` NVARCHAR(45) NOT NULL,
  PRIMARY KEY (`AccountId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
